# ==========================================================
#  UART Design - Top-Level Makefile
#  Auto-generated by create_uart_project.py
# ==========================================================

# List of subdirectories with Makefiles
SUBDIRS := filelist gen_filelist scripts/proj_setup scripts/tool_setup static/lint static/cdc static/rdc static/vc_formal verif/vcs verif/tests verif/testcase synth/fc

.PHONY: all clean $(SUBDIRS)

# Default target
all: $(SUBDIRS)
	@echo "✅ UART project build completed."

# Recursively call 'make' in subdirectories
$(SUBDIRS):
	@echo "🔧 Entering directory '$@'"
	@$(MAKE) -C $@ all

# Clean target to remove build files recursively
clean:
	@for dir in $(SUBDIRS); do \
		$(MAKE) -C $$dir clean; \
	done
	@echo "🧹 Cleaned all subdirectories."
